// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfdhihjcdrgfahkbszdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmZGhpaGpjZHJnZmFoa2JzemRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTcyODcsImV4cCI6MjA2MTEzMzI4N30.5U9bnTPUT69f8qd3JUxBetl8T5W47-yZxO21JgTdbe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);